name: Deploy

on:
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: Build, Lint & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Run linters
        run: |
          npm run typecheck &&  npm run lint
      - name: Run e2e tests
        run: |
          npm run test:e2e:ci