name: Push
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE
    branches:
      - 'main'

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: dolf.me