name: Push
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE
    branches:
      - 'main'
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "mail@dolf.me"
          git config --global user.name "Dolf Barr"
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: npm ci
      - name: Deploy
        run: npm run deploy